### ISSUE TITLE
Missing SOVERSION minor bump

### ISSUE THREAD

**Issue by stewartsmith** [awslabs/aws-c-sdkutils#10]
Looking at https://github.com/awslabs/aws-c-sdkutils/commit/e3c23f4aca31d9e66df25827645f72cbcbfb657a it looks like a functional (yet backwards compatible) change has been introduced between 0.1.1 and 0.1.2, which should mean that the minor SONAME version should have been incremented, so that any application relying on this new behavior would be sure to link to the correct shared library.

**Comment by jmklix** [comment]
Sorry for the late reply. We have since bumped the version to [v0.9.23](https://github.com/awslabs/aws-c-common/tree/v0.9.23). So I don't think this is a concern anymore. Please let me know if you have any questions about versioning with this sdk
