### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by daniloegea** [awslabs/aws-c-sdkutils#5]
Any chance to add a description of what this project is used for? :)

**Comment by yasminetalby** [comment]
Hello @daniloegea ,

Thank you very much for your submission. My sincere apologies for the delay of answer on this issue.

A description of the project has been added in [v0.1.12](https://github.com/awslabs/aws-c-sdkutils/commit/2d9ef421f88ab9599f1a128fd4567c2ada64a6b8). 

If you'd like to provide some feedback or have any question/request for further documentation please let me know!

Thank you very much for your time and collaboration.

Sincerely,

Yasmine
